import { USER_ROLES, BUS_STATUS, ROUTE_STATUS, REPORT_STATUS } from './constants';

// Mock Users
export const mockUsers = [
  {
    id: '1',
    name: 'Arpit Anand',
    email: 'arpit@example.com',
    phone: '9876543210',
    role: USER_ROLES.PASSENGER,
    trustScore: 450,
    points: 1250,
    reportsSubmitted: 45,
    reportsApproved: 38,
    avatar: null,
    joinedDate: '2024-01-15',
    isActive: true,
  },
  {
    id: '2',
    name: 'Rahul Kumar',
    email: 'rahul.driver@example.com',
    phone: '9876543211',
    role: USER_ROLES.DRIVER,
    licenseNumber: 'DL1420110012345',
    busAssigned: 'DL-1PC-1234',
    rating: 4.5,
    tripsCompleted: 234,
    joinedDate: '2023-06-20',
    isActive: true,
  },
  {
    id: '3',
    name: 'Admin User',
    email: 'admin@whereismybus.com',
    phone: '9876543212',
    role: USER_ROLES.ADMIN,
    joinedDate: '2023-01-01',
    isActive: true,
  },
  {
    id: '4',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '9876543213',
    role: USER_ROLES.PASSENGER,
    trustScore: 720,
    points: 2100,
    reportsSubmitted: 82,
    reportsApproved: 78,
    avatar: null,
    joinedDate: '2023-11-10',
    isActive: true,
  },
  {
    id: '5',
    name: 'Amit Singh',
    email: 'amit.driver@example.com',
    phone: '9876543214',
    role: USER_ROLES.DRIVER,
    licenseNumber: 'DL1420110012346',
    busAssigned: 'DL-1PC-5678',
    rating: 4.8,
    tripsCompleted: 456,
    joinedDate: '2023-03-15',
    isActive: true,
  },
];

// Mock Routes
export const mockRoutes = [
  {
    id: 'route1',
    routeNumber: '764',
    name: 'Connaught Place - Nehru Place',
    startPoint: 'Connaught Place',
    endPoint: 'Nehru Place',
    distance: 14.5,
    estimatedDuration: 45,
    fare: 20,
    status: ROUTE_STATUS.ACTIVE,
    stops: [
      { id: 'stop1', name: 'Connaught Place', lat: 28.6315, lng: 77.2167, order: 1 },
      { id: 'stop2', name: 'ITO', lat: 28.6289, lng: 77.2496, order: 2 },
      { id: 'stop3', name: 'Lajpat Nagar', lat: 28.5677, lng: 77.2431, order: 3 },
      { id: 'stop4', name: 'Moolchand', lat: 28.5722, lng: 77.2514, order: 4 },
      { id: 'stop5', name: 'Nehru Place', lat: 28.5494, lng: 77.2501, order: 5 },
    ],
    frequency: '10-15 minutes',
    operatingHours: '06:00 - 23:00',
    busesAssigned: 8,
  },
  {
    id: 'route2',
    routeNumber: '534',
    name: 'Kashmere Gate - Anand Vihar',
    startPoint: 'Kashmere Gate',
    endPoint: 'Anand Vihar ISBT',
    distance: 18.2,
    estimatedDuration: 55,
    fare: 25,
    status: ROUTE_STATUS.ACTIVE,
    stops: [
      { id: 'stop6', name: 'Kashmere Gate', lat: 28.6692, lng: 77.2289, order: 1 },
      { id: 'stop7', name: 'Shastri Park', lat: 28.6709, lng: 77.2822, order: 2 },
      { id: 'stop8', name: 'Dilshad Garden', lat: 28.6815, lng: 77.3190, order: 3 },
      { id: 'stop9', name: 'New Ashok Nagar', lat: 28.6459, lng: 77.3091, order: 4 },
      { id: 'stop10', name: 'Anand Vihar ISBT', lat: 28.6469, lng: 77.3161, order: 5 },
    ],
    frequency: '15-20 minutes',
    operatingHours: '05:30 - 23:30',
    busesAssigned: 6,
  },
  {
    id: 'route3',
    routeNumber: '413',
    name: 'Rajouri Garden - Saket',
    startPoint: 'Rajouri Garden',
    endPoint: 'Saket District Centre',
    distance: 22.3,
    estimatedDuration: 70,
    fare: 30,
    status: ROUTE_STATUS.ACTIVE,
    stops: [
      { id: 'stop11', name: 'Rajouri Garden', lat: 28.6410, lng: 77.1199, order: 1 },
      { id: 'stop12', name: 'Punjabi Bagh', lat: 28.6692, lng: 77.1312, order: 2 },
      { id: 'stop13', name: 'Dhaula Kuan', lat: 28.5967, lng: 77.1613, order: 3 },
      { id: 'stop14', name: 'AIIMS', lat: 28.5677, lng: 77.2089, order: 4 },
      { id: 'stop15', name: 'Saket District Centre', lat: 28.5244, lng: 77.2066, order: 5 },
    ],
    frequency: '12-18 minutes',
    operatingHours: '06:00 - 22:30',
    busesAssigned: 10,
  },
];

// Mock Buses
export const mockBuses = [
  {
    id: 'bus1',
    registrationNumber: 'DL-1PC-1234',
    routeId: 'route1',
    routeNumber: '764',
    currentLocation: { lat: 28.6289, lng: 77.2496 },
    currentStop: 'ITO',
    nextStop: 'Lajpat Nagar',
    status: BUS_STATUS.ACTIVE,
    speed: 32,
    passengerCount: 28,
    capacity: 50,
    driver: {
      id: '2',
      name: 'Rahul Kumar',
      phone: '9876543211',
    },
    lastUpdated: new Date().toISOString(),
    eta: 12, // minutes to next stop
  },
  {
    id: 'bus2',
    registrationNumber: 'DL-1PC-5678',
    routeId: 'route2',
    routeNumber: '534',
    currentLocation: { lat: 28.6709, lng: 77.2822 },
    currentStop: 'Shastri Park',
    nextStop: 'Dilshad Garden',
    status: BUS_STATUS.ACTIVE,
    speed: 28,
    passengerCount: 35,
    capacity: 50,
    driver: {
      id: '5',
      name: 'Amit Singh',
      phone: '9876543214',
    },
    lastUpdated: new Date().toISOString(),
    eta: 8,
  },
  {
    id: 'bus3',
    registrationNumber: 'DL-1PC-9012',
    routeId: 'route1',
    routeNumber: '764',
    currentLocation: { lat: 28.5677, lng: 77.2431 },
    currentStop: 'Lajpat Nagar',
    nextStop: 'Moolchand',
    status: BUS_STATUS.ACTIVE,
    speed: 25,
    passengerCount: 42,
    capacity: 50,
    driver: {
      id: '2',
      name: 'Rahul Kumar',
      phone: '9876543211',
    },
    lastUpdated: new Date().toISOString(),
    eta: 5,
  },
  {
    id: 'bus4',
    registrationNumber: 'DL-1PC-3456',
    routeId: 'route3',
    routeNumber: '413',
    currentLocation: { lat: 28.5967, lng: 77.1613 },
    currentStop: 'Dhaula Kuan',
    nextStop: 'AIIMS',
    status: BUS_STATUS.DELAYED,
    speed: 15,
    passengerCount: 38,
    capacity: 50,
    driver: {
      id: '5',
      name: 'Amit Singh',
      phone: '9876543214',
    },
    lastUpdated: new Date().toISOString(),
    eta: 18,
  },
  {
    id: 'bus5',
    registrationNumber: 'DL-1PC-7890',
    routeId: 'route2',
    routeNumber: '534',
    currentLocation: { lat: 28.6692, lng: 77.2289 },
    currentStop: 'Kashmere Gate',
    nextStop: 'Shastri Park',
    status: BUS_STATUS.ACTIVE,
    speed: 30,
    passengerCount: 22,
    capacity: 50,
    driver: {
      id: '2',
      name: 'Rahul Kumar',
      phone: '9876543211',
    },
    lastUpdated: new Date().toISOString(),
    eta: 10,
  },
];

// Mock Reports
export const mockReports = [
  {
    id: 'report1',
    busId: 'bus1',
    busNumber: 'DL-1PC-1234',
    routeNumber: '764',
    reportedBy: {
      id: '1',
      name: 'Arpit Anand',
    },
    location: {
      name: 'ITO',
      lat: 28.6289,
      lng: 77.2496,
    },
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 mins ago
    photo: null,
    description: 'Bus spotted at ITO stop, heading towards Nehru Place',
    status: REPORT_STATUS.APPROVED,
    pointsAwarded: 20,
    validatedBy: 'admin@whereismybus.com',
    validatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: 'report2',
    busId: 'bus2',
    busNumber: 'DL-1PC-5678',
    routeNumber: '534',
    reportedBy: {
      id: '4',
      name: 'Priya Sharma',
    },
    location: {
      name: 'Shastri Park',
      lat: 28.6709,
      lng: 77.2822,
    },
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 mins ago
    photo: null,
    description: 'Bus at Shastri Park metro station',
    status: REPORT_STATUS.PENDING,
    pointsAwarded: 0,
  },
  {
    id: 'report3',
    busId: 'bus3',
    busNumber: 'DL-1PC-9012',
    routeNumber: '764',
    reportedBy: {
      id: '1',
      name: 'Arpit Anand',
    },
    location: {
      name: 'Lajpat Nagar',
      lat: 28.5677,
      lng: 77.2431,
    },
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(), // 25 mins ago
    photo: null,
    description: 'Bus reached Lajpat Nagar central market',
    status: REPORT_STATUS.APPROVED,
    pointsAwarded: 20,
    validatedBy: 'admin@whereismybus.com',
    validatedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
];

// Mock Badges
export const mockBadges = [
  {
    id: 'badge1',
    name: 'First Report',
    description: 'Submit your first bus sighting report',
    icon: '🎯',
    unlockedAt: '2024-01-16',
    rarity: 'common',
  },
  {
    id: 'badge2',
    name: 'Reporter - 10',
    description: 'Submit 10 verified bus reports',
    icon: '🏆',
    unlockedAt: '2024-02-05',
    rarity: 'uncommon',
  },
  {
    id: 'badge3',
    name: 'Community Helper',
    description: 'Help 100 people find their bus',
    icon: '🤝',
    unlockedAt: '2024-03-20',
    rarity: 'rare',
  },
  {
    id: 'badge4',
    name: 'Accuracy Master',
    description: 'Maintain 95% report accuracy',
    icon: '⭐',
    unlockedAt: null,
    rarity: 'epic',
  },
];

// Mock Leaderboard
export const mockLeaderboard = [
  {
    rank: 1,
    userId: '4',
    name: 'Priya Sharma',
    points: 2100,
    reportsSubmitted: 82,
    trustScore: 720,
    avatar: null,
  },
  {
    rank: 2,
    userId: '6',
    name: 'Rajesh Verma',
    points: 1850,
    reportsSubmitted: 71,
    trustScore: 650,
    avatar: null,
  },
  {
    rank: 3,
    userId: '1',
    name: 'Arpit Anand',
    points: 1250,
    reportsSubmitted: 45,
    trustScore: 450,
    avatar: null,
  },
  {
    rank: 4,
    userId: '7',
    name: 'Sneha Gupta',
    points: 980,
    reportsSubmitted: 38,
    trustScore: 380,
    avatar: null,
  },
  {
    rank: 5,
    userId: '8',
    name: 'Vikram Singh',
    points: 750,
    reportsSubmitted: 29,
    trustScore: 310,
    avatar: null,
  },
];

// Mock Challenges
export const mockChallenges = [
  {
    id: 'challenge1',
    title: 'Daily Reporter',
    description: 'Submit 5 bus reports today',
    reward: 100,
    progress: 3,
    target: 5,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 10).toISOString(), // 10 hours from now
    icon: '📍',
    status: 'active',
  },
  {
    id: 'challenge2',
    title: 'Peak Hour Helper',
    description: 'Report 10 buses during peak hours (8-10 AM, 6-8 PM)',
    reward: 200,
    progress: 7,
    target: 10,
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(), // 7 days
    icon: '⏰',
    status: 'active',
  },
  {
    id: 'challenge3',
    title: 'Route Explorer',
    description: 'Report buses from 5 different routes',
    reward: 150,
    progress: 5,
    target: 5,
    expiresAt: null,
    icon: '🗺️',
    status: 'completed',
  },
];

// Mock Messages (for driver)
export const mockMessages = [
  {
    id: 'msg1',
    from: {
      id: '1',
      name: 'Arpit Anand',
      avatar: null,
    },
    to: {
      id: '2',
      name: 'Rahul Kumar',
    },
    message: 'When will the bus reach ITO?',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    isRead: true,
  },
  {
    id: 'msg2',
    from: {
      id: '4',
      name: 'Priya Sharma',
      avatar: null,
    },
    to: {
      id: '2',
      name: 'Rahul Kumar',
    },
    message: 'Is there space available in the bus?',
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    isRead: false,
  },
  {
    id: 'msg3',
    from: {
      id: '9',
      name: 'Ravi Kumar',
      avatar: null,
    },
    to: {
      id: '2',
      name: 'Rahul Kumar',
    },
    message: 'Thank you for the smooth ride!',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    isRead: true,
  },
];

// Mock Driver Performance
export const mockDriverPerformance = {
  driverId: '2',
  name: 'Rahul Kumar',
  stats: {
    totalTrips: 234,
    completedTrips: 228,
    cancelledTrips: 6,
    averageRating: 4.5,
    totalRatings: 189,
    onTimePercentage: 92,
    passengersServed: 11240,
    totalDistance: 3456,
  },
  recentTrips: [
    {
      id: 'trip1',
      date: '2024-10-01',
      route: '764',
      startTime: '08:00',
      endTime: '08:45',
      distance: 14.5,
      passengers: 42,
      rating: 4.8,
      status: 'completed',
    },
    {
      id: 'trip2',
      date: '2024-10-01',
      route: '764',
      startTime: '09:15',
      endTime: '10:00',
      distance: 14.5,
      passengers: 38,
      rating: 4.5,
      status: 'completed',
    },
    {
      id: 'trip3',
      date: '2024-10-01',
      route: '764',
      startTime: '10:30',
      endTime: '11:15',
      distance: 14.5,
      passengers: 35,
      rating: 4.6,
      status: 'completed',
    },
  ],
  weeklyPerformance: [
    { day: 'Mon', trips: 12, rating: 4.5 },
    { day: 'Tue', trips: 14, rating: 4.6 },
    { day: 'Wed', trips: 13, rating: 4.4 },
    { day: 'Thu', trips: 15, rating: 4.7 },
    { day: 'Fri', trips: 14, rating: 4.5 },
    { day: 'Sat', trips: 10, rating: 4.3 },
    { day: 'Sun', trips: 8, rating: 4.6 },
  ],
};

// Mock Analytics Data
export const mockAnalytics = {
  dashboardStats: {
    totalUsers: 12450,
    activeUsers: 8320,
    totalDrivers: 234,
    activeDrivers: 189,
    totalBuses: 156,
    activeBuses: 142,
    totalRoutes: 45,
    activeRoutes: 42,
    todayReports: 328,
    pendingReports: 42,
    approvedReports: 286,
  },
  userGrowth: [
    { month: 'Jan', users: 2340 },
    { month: 'Feb', users: 3120 },
    { month: 'Mar', users: 4230 },
    { month: 'Apr', users: 5680 },
    { month: 'May', users: 7120 },
    { month: 'Jun', users: 8560 },
    { month: 'Jul', users: 9880 },
    { month: 'Aug', users: 11200 },
    { month: 'Sep', users: 12450 },
  ],
  routePopularity: [
    { route: '764', trips: 1245, passengers: 45678 },
    { route: '534', trips: 987, passengers: 38902 },
    { route: '413', trips: 876, passengers: 34567 },
    { route: '522', trips: 765, passengers: 29876 },
    { route: '340', trips: 654, passengers: 25432 },
  ],
  reportsTimeline: [
    { date: '2024-09-25', reports: 234 },
    { date: '2024-09-26', reports: 278 },
    { date: '2024-09-27', reports: 312 },
    { date: '2024-09-28', reports: 289 },
    { date: '2024-09-29', reports: 345 },
    { date: '2024-09-30', reports: 298 },
    { date: '2024-10-01', reports: 328 },
  ],
};

// Export all mock data
export default {
  mockUsers,
  mockRoutes,
  mockBuses,
  mockReports,
  mockBadges,
  mockLeaderboard,
  mockChallenges,
  mockMessages,
  mockDriverPerformance,
  mockAnalytics,
};
